import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../styles/global.scss";
import Nav from "./components/navigations";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "socon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
