import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../styles/global.scss";
import Nav from "./components/navigations";
import SideNav from "./components/navigations/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "socon",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        alt: "socon thumbnail",
        url: "https://github.com/Poylib/socon/assets/100523313/4c334b52-930c-4b20-a0a3-81e92e21f686",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Nav />
        <SideNav />
        {children}
      </body>
    </html>
  );
}
